# Generated by Django 3.2.9 on 2021-11-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ratings',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
