# Generated by Django 3.2.9 on 2021-11-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField(unique=True)),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('released_date', models.DateTimeField()),
                ('popularity', models.FloatField()),
                ('vote_avg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('overview', models.TextField(null=True)),
                ('poster_path', models.CharField(max_length=200, null=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
    ]
