# Generated by Django 3.2.9 on 2021-11-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
