# Generated by Django 3.2.9 on 2021-11-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
