# Generated by Django 3.2.9 on 2021-11-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-popularity']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='released_date',
            field=models.DateField(),
        ),
    ]
