# Generated by Django 3.2.9 on 2021-11-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
