# Generated by Django 3.2.9 on 2021-11-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_user_id_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_review',
        ),
        migrations.RemoveField(
            model_name='article',
            name='movie_id',
        ),
    ]
