# Generated by Django 3.2.9 on 2021-11-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20211119_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kmovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('vote_count', models.IntegerField()),
                ('poster_path', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-vote_count'],
            },
        ),
    ]
